<?php

/**
 * @file
 * Primary module hooks for OUM Marker.io module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_page_attachments().
 */
function markerio_page_attachments(&$attachments) {
  $destination = \Drupal::config('markerio.settings')->get('destination');
  if (\Drupal::currentUser()->isAuthenticated()
      && \Drupal::currentUser()->hasPermission('access marker io')
      && isset($destination)) {
    $attachments['#attached']['library'][] = 'markerio/markerio';
    $attachments['#attached']['drupalSettings']['markerio']['destination'] = $destination;
  }
}
