<?php

/**
 * @file
 * Primary module hooks for OUM Marker.io module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_page_attachments().
 */
function markerio_page_attachments(&$attachments) {
  $destination = \Drupal::config('markerio.settings')->get('destination');

  $user = \Drupal::currentUser();

  if ($user->hasPermission('access markerio') && isset($destination)) {
    // get username and e-mailaddress
    $user_email = false;
    $user_name = false;

    if ($user->isAuthenticated()) {
      $user_email = $user->getEmail();
      $user_name = $user->getDisplayName();
    }
    
    // prepare javasript
    $attachments['#attached']['library'][] = 'markerio/markerio';
    $attachments['#attached']['drupalSettings']['markerio']['destination'] = $destination;
    $attachments['#attached']['drupalSettings']['markerio']['user_email'] = $user_email;
    $attachments['#attached']['drupalSettings']['markerio']['user_name'] = $user_name;
  }
}
