<?php

/**
 * @file
 * Primary module hooks for OUM Marker.io module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_page_attachments().
 */
function oum_marker_io_page_attachments(&$attachments) {
  $destination = \Drupal::config('oum_marker_io.settings')->get('destination');
  if (\Drupal::currentUser()->isAuthenticated() && isset($destination)) {
    $attachments['#attached']['library'][] = 'oum_marker_io/oum_marker_io';
    $attachments['#attached']['drupalSettings']['oum_marker_io']['destination'] = $destination;
  }
}
